#!/bin/bash
set -eu
# Check directory
cd "$(dirname "$0")"
[ -d .git ] || cd ../..
[ -d .git ]

pre_commit() {
	flake8
	black --check .
	isort --check-only .
}

case "${1:-run}" in
	run)
		pre_commit
		echo "All good to commit"
		;;
	install)
		echo "Installing pre-commit"
		cd .git/hooks
		ln -sf ../../pre-commit pre-commit
		;;
	uninstall)
		echo "Uninstalling pre-commit"
		rm -f .git/hooks/pre-commit
		;;
	*)
		echo "Invalid command: $*"
		echo "Supported options: install, uninstall"
esac
