name: Lint and test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run pre-commit checks
      run: |
        ./pre-commit
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # lowest, common (default ubuntu LTS), newest
        python-version: ["3.7", "3.8", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest --doctest-modules
    - name: Run mypy
      run: |
        mypy --install-types --non-interactive .
